### ISSUE TITLE
Epic - Entrée bénéficiaire

### ISSUE THREAD

**Issue by Augustin82** [gip-inclusion/carnet-de-bord#615]
- [ ] login (par quel moyen ?) => email pour l'instant, on verra après
- [ ] vue de son propre carnet uniquement sans accès à l'édition
- [ ] possibilité d'imprimer le Carnet ?
